### ISSUE TITLE
全局唯一ID生成强化

### ISSUE THREAD

**Issue by vilinian** [JunahW/gamedemo#70]
现在只依赖于时间戳太慢了, 只能到毫秒级, 是不符合需求的, 
可能一瞬间创建100个物品,需要生成100个唯一ID,你这个需要100毫秒, 太慢了
想办法优化

**Comment by JunahW** [comment]
![image](https://user-images.githubusercontent.com/32157679/59811371-29326480-933c-11e9-835b-3f93a1c489e0.png)同一毫秒内若出现重复，则会进行递增，递增占12bit，理论上单机一秒可以产生  1000*（2^12）= 4096000 个唯一序列码。
